#!/usr/bin/env python3
"""Regenerate the pinned dependency locks from the direct choices.

Two locks, each produced in the environment that installs it, because a lock resolved on a
developer's machine describes that machine:

``apps/api/requirements.lock.txt``  the backend and the worker, frozen from an install of
                                    `apps/api/requirements.txt` into the API image's own Python.
``apps/web/package-lock.json``      the frontend, resolved by npm in the toolchain image.

Run this after changing `requirements.txt` or `package.json`, then rebuild and record the change in
`docs/VERSIONS.md`.

    python scripts/iacode/lock_dependencies.py
    python scripts/iacode/lock_dependencies.py --only backend
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from compose import REPOSITORY_ROOT, StackError, log, main_guard, require_docker

PYTHON_IMAGE = "python:3.13.15-slim-bookworm"
NODE_IMAGE = "node:22.23.2-bookworm-slim"
NPM_VERSION = "12.0.2"

HEADER = """# Resolved dependency lock for the IACode API and worker images.
#
# Produced by installing apps/api/requirements.txt into the image's own Python and freezing the
# result, so it records what that install actually resolves to on this base image rather than what
# a developer's machine happens to have. Regenerate with:
#
#     python scripts/iacode/lock_dependencies.py
#
# Direct choices live in apps/api/requirements.txt. Do not edit this file by hand.
"""


def backend() -> None:
    log("resolving the backend dependencies in the image's own Python")
    completed = subprocess.run(
        ["docker", "run", "--rm",
         "--volume", f"{REPOSITORY_ROOT / 'apps' / 'api'}:/src:ro",
         PYTHON_IMAGE, "sh", "-c",
         "python -m venv /v >/dev/null && "
         "/v/bin/pip install --no-cache-dir -q -r /src/requirements.txt && "
         "/v/bin/pip freeze --exclude-editable"],
        text=True, encoding="utf-8", errors="replace",
        capture_output=True, check=False)
    if completed.returncode != 0:
        raise StackError("the backend dependencies could not be resolved:\n"
                         + (completed.stderr or "").strip()[-1500:])
    frozen = sorted((line.strip() for line in completed.stdout.splitlines() if line.strip()),
                    key=str.lower)
    target = REPOSITORY_ROOT / "apps" / "api" / "requirements.lock.txt"
    target.write_text(HEADER + "\n".join(frozen) + "\n", encoding="utf-8", newline="\n")
    log(f"wrote {target.relative_to(REPOSITORY_ROOT)} with {len(frozen)} pinned package(s)")


def frontend() -> None:
    log("resolving the frontend dependencies with npm")
    web = REPOSITORY_ROOT / "apps" / "web"
    completed = subprocess.run(
        ["docker", "run", "--rm",
         "--volume", f"{web}:/out",
         NODE_IMAGE, "sh", "-c",
         # The npm that ships with this Node image cannot resolve this tree; the upgrade is
         # load-bearing and is pinned for the same reason every other version here is.
         f"npm install --global npm@{NPM_VERSION} >/dev/null 2>&1 && "
         "mkdir -p /app && cp /out/package.json /app/ && cd /app && "
         "npm install --package-lock-only --ignore-scripts >/dev/null && "
         "cp /app/package-lock.json /out/package-lock.json"],
        text=True, encoding="utf-8", errors="replace",
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    if completed.returncode != 0:
        raise StackError("the frontend dependencies could not be resolved:\n"
                         + completed.stdout.strip()[-1500:])
    log("wrote apps/web/package-lock.json")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", choices=("backend", "frontend"), default=None)
    arguments = parser.parse_args()

    require_docker()
    if arguments.only in (None, "backend"):
        backend()
    if arguments.only in (None, "frontend"):
        frontend()
    log("LOCK=OK — rebuild the images and record the change in docs/VERSIONS.md")
    return 0


if __name__ == "__main__":
    main_guard(main)
