"""The declarative base and the column conventions every IACode table follows.

Two conventions, and the boundary between them matters:

:class:`Base`       naming conventions for constraints and indexes. Applied to every table without
                    exception, because Alembic needs a deterministic name to drop a constraint it
                    did not create, and PostgreSQL's auto-generated names are not deterministic
                    across environments.

:class:`TimestampedEntity`  ``id``, ``created_at``, ``updated_at``, ``version`` and ``metadata_``.
                    Applied to the entities that have a lifecycle.

`docs/GATE-0-CHECKLIST.md` row 5.8 asks for a convention that is defined once and applied where it
makes sense, *not* forced everywhere for the sake of uniformity. So the append-only records —
``model_calls``, ``tool_calls``, ``experiences`` — use :class:`ImmutableRecord` instead: they are
facts about something that already happened. An ``updated_at`` on a fact that cannot change invites
code to update it, and an optimistic-locking ``version`` on a row nobody locks is noise.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, ClassVar

from iacode_common.identifiers import uuid7
from sqlalchemy import BigInteger, DateTime, MetaData, func
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint names. Without them Alembic emits migrations that cannot be reversed,
# because the downgrade has no stable name to reference.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base carrying the naming convention and nothing else."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    # A declarative class attribute by design: SQLAlchemy reads it off the class, and annotating
    # it as a ClassVar is how that intent is stated rather than silenced.
    type_annotation_map: ClassVar[dict] = {
        dict[str, Any]: JSONB,
        uuid.UUID: postgresql.UUID(as_uuid=True),
    }


class IdentifiedEntity:
    """A UUIDv7 primary key, generated by the application rather than by the database.

    Generating identifiers in Python is what lets a caller know the key before the insert, and what
    keeps the strategy identical across every process. ``packages/common`` owns the generator, so
    the API, the worker and every future service produce the same shape.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        postgresql.UUID(as_uuid=True), primary_key=True, default=uuid7,
        doc="UUIDv7 primary key: globally unique and ordered by creation time.")


class TimestampedEntity(IdentifiedEntity):
    """An entity with a lifecycle: it is created, it changes, and the change is tracked."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())
    version: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=1, server_default="1",
        doc="Optimistic-locking counter, incremented by the writer that changes the row.")
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, default=dict, server_default="{}",
        doc="Open extension point for attributes a later Gate needs before it has a column.")


class ImmutableRecord(IdentifiedEntity):
    """An append-only fact. It has a creation time and no update time, because it never changes."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now())
